default:
    prefix: /
    resource: '../src/Controller'

api:
    prefix: /api
    resource: '../src/Controller/Api'

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
